name: 报告问题
description: 提 issue 报告问题，请点击右边绿色按钮
labels: ["bug"]
title: "请修改这里的名称"
assignees:
  - octocat
body:
  - type: checkboxes
    id: lists
    attributes:
      label: 清单
      description: 你必须按要求尝试并勾选完成。
      options:
        - label: 我已经仔细阅读过 README 说明 https://github.com/TechXueXi/techxuexi-js
          required: true
        - label: 我已经查看/搜索过所有已有 issue，无论是open还是close的 https://github.com/TechXueXi/techxuexi-js/issues?q=is%3Aissue
          required: true
        - label: 我已经通过搜索引擎搜索，尝试不同的关键词   www.google.com  www.baidu.com
          required: true
        - label: 我已经到提供的在线聊天室询问过  聊天室说明：https://github.com/TechXueXi/TechXueXi/issues/14
          required: true
  - type: input
    id: js-name
    attributes:
      label: 脚本名称
      description: 如 不学习何以强国.js
      placeholder: 不学习何以强国.js
    validations:
      required: true
  - type: input
    id: source-version
    attributes:
      label: 软件/源码版本
      description: js文件的“// @version      20211223”是版本号
      placeholder: 20211223
    validations:
      required: true
  - type: input
    id: sys-version
    attributes:
      label: 系统版本，包含位数
      description: 如 windows x64 , centos x64，debain arm32
      placeholder: windows x64
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: 浏览器版本
      description: 如 chrome v73.0.0
      placeholder: chrome v73.0.0
    validations:
      required: true
  - type: input
    id: e-version
    attributes:
      label: 油猴等插件版本
      description: 油猴在管理面板的左上角图标处可以看到，如 v4.11
      placeholder: v4.11
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 详细描述
      description: 报错请复制粘贴，可以粘贴图片，但不要只使用图片，方便同志们搜索。
      placeholder:
      value:
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        **必须填写完成才能按提交按钮**
      
        许多IT人员本终日埋头写代码，对我们这类软件确实有需求，
        与其各人重复修改编写浪费生产力不如团队合作维护，因此我们希望长期维护此生态。
        有意愿加入本组织者，请 https://techxuexi.js.org/
        
        我们不接受任何捐赠。远离非法牟利。
